### ISSUE TITLE
Update to tdlib/td 1.3.0

### ISSUE THREAD

**Issue by Fnux** [oott123/tdlib-json-cli#4]
Hello,

[tdlib 1.3.0](https://github.com/tdlib/td/releases/tag/v1.3.0)  is now available: it would be nice to bump the tdlib version used in this project.

Thanks,

**Comment by oott123** [comment]
Hi, thanks for your nice issue.
I'd like to have tdlib 1.3.0 if someone made a pull request. Can you make a pull request?

**Comment by Fnux** [comment]
I'll take a look when I get some free time then.

**Comment by gammaalfa** [comment]
Any news so far? =) It's 1.4.0 already. I wish I could do it by myself.

**Comment by oott123** [comment]
@gammaalfa feel free to send PRs if you'd like to do :)

**Comment by gammaalfa** [comment]
@oott123 I really wish to but have zero knowledge in cpp

**Comment by gammaalfa** [comment]
> @gammaalfa feel free to send PRs if you'd like to do :)

If I got it right, all I have to do is replace ```td/``` folder with newer tdlib version and generate ```types.json``` using ```types-generator```. ```types-generator```'s ```index.js``` parses some html docs saved as files. Where did you get those files from? Is there a quick way to do this or do i have to rewrite ```types-generator``` from the ground up to parse html docs?

**Comment by oott123** [comment]
@gammaalfa types-generator is using the tdlib generated docs to genenrate `types.json`.
I'm not sure whether types-generator will work now or not since they rewrite the documents template completely, but if it don't works, we can just remove it from this repo. types.json is not necessary for tdlib-json-cli to work.

Yes the only thing you have to do is update tdlib using git submodule. It will be somehow difficult if you don't have any experience for cpp, but if you have some experiences for building programs on Linux platform, you are ok to build this project using those experiences.

**Comment by gammaalfa** [comment]
> we can just remove it from this repo

That's funny, actually it is @Fnux's library ```elixir-tdlib``` brought me here. It relies on your tool as an external dependency and in order to make calls to it, Elixir's data structs has to be created, which is why ```types.json``` is being parsed in his lib.

Since some of methods seems to be deprecated and doesn't work in current version, update is needed. For example, methods to set up socks proxy doesn't seem to work anymore as they have been deprecated in favour of new ones and thats a pretty critical issue I must say.

So it is either a task to update parse as well as ```tdlib``` or a task to utilize native ```tdlib``` CLI inside @fnux's lib. As far as I see it now going through first one might be easier but speaking of robustness might be not the best way to go. 

Any way, as well as @fnux has been planning to take a look into the issue I will try sadly with no guarantees so far due to my knowledge limitations =/

**Comment by oott123** [comment]
Ah, I don't know that there are someone relies on it, thank you for pointed this out.

Actually the types-generator is a bit shabby because I only have one hour to write it and I even never carefully test it. Maybe someone can rewrite it, I don't have any time to do that recently :(

**Comment by Fnux** [comment]
This elixir binding is quite simple as it only offers convenience elixir modules to interact with tdlib. I do not use this tool anymore/for now and do not have enough time to do it myself but would gladly answer your questions/help you on a few things.

**Comment by gammaalfa** [comment]
@oott123 https://github.com/oott123/tdlib-json-cli/pull/5

**Comment by oott123** [comment]
fixed via #5
